version: '3.8'

services:
    db:
        image: postgres
        restart: always
        ports:
            - 5432:5432
        volumes:
            - postgres_data:/var/lib/posgresql/data/
        environment:
            - POSTGRES_PASSWORD=secret

    adminer:
        image: adminer
        restart: always
        ports:
            - 8081:8080
        depends_on:
            - db

volumes:
    postgres_data: